# Generated by Django 3.1.7 on 2021-03-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rofl', '0004_auto_20210324_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt', models.TextField(verbose_name='токен пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rofl.answer', verbose_name='ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rofl.question', verbose_name='вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rofl.user', verbose_name='пользователь')),
            ],
        ),
    ]
