# Generated by Django 3.1.7 on 2021-03-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rofl', '0006_auto_20210327_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='faculty',
        ),
        migrations.AddField(
            model_name='answer',
            name='faculty',
            field=models.ManyToManyField(to='rofl.Faculty', verbose_name='факультет'),
        ),
    ]
