# Generated by Django 3.1.7 on 2021-03-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rofl', '0009_auto_20210331_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='link_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
