# Generated by Django 3.1.7 on 2021-03-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_auto_20210327_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.CharField(default='Ваш факультет <django.db.models.fields.CharField>', max_length=1500, verbose_name='Текст для репоста'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='link_pic',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
