# Generated by Django 3.1.7 on 2021-03-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_auto_20210329_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='link_pic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
