# Generated by Django 3.1.7 on 2021-03-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0010_auto_20210331_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='link_pic',
            field=models.CharField(max_length=30, verbose_name='название файла'),
        ),
    ]
